package com.crm.entity;

import java.math.BigDecimal;

public class BasDict {
    /**
     *
     * 编号
     */
    private Integer dictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BAS_DICT.DICT_TYPE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String dictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BAS_DICT.DICT_ITEM
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String dictItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BAS_DICT.DICT_VALUE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String dictValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BAS_DICT.DICT_IS_EDITABLE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private BigDecimal dictIsEditable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAS_DICT.DICT_ID
     *
     * @return the value of BAS_DICT.DICT_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public Integer getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAS_DICT.DICT_ID
     *
     * @param dictId the value for BAS_DICT.DICT_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setDictId(Integer dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAS_DICT.DICT_TYPE
     *
     * @return the value of BAS_DICT.DICT_TYPE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAS_DICT.DICT_TYPE
     *
     * @param dictType the value for BAS_DICT.DICT_TYPE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAS_DICT.DICT_ITEM
     *
     * @return the value of BAS_DICT.DICT_ITEM
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getDictItem() {
        return dictItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAS_DICT.DICT_ITEM
     *
     * @param dictItem the value for BAS_DICT.DICT_ITEM
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setDictItem(String dictItem) {
        this.dictItem = dictItem == null ? null : dictItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAS_DICT.DICT_VALUE
     *
     * @return the value of BAS_DICT.DICT_VALUE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAS_DICT.DICT_VALUE
     *
     * @param dictValue the value for BAS_DICT.DICT_VALUE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue == null ? null : dictValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAS_DICT.DICT_IS_EDITABLE
     *
     * @return the value of BAS_DICT.DICT_IS_EDITABLE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public BigDecimal getDictIsEditable() {
        return dictIsEditable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAS_DICT.DICT_IS_EDITABLE
     *
     * @param dictIsEditable the value for BAS_DICT.DICT_IS_EDITABLE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setDictIsEditable(BigDecimal dictIsEditable) {
        this.dictIsEditable = dictIsEditable;
    }
}