package com.crm.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CstActivity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_ACTIVITY.ATV_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private BigDecimal atvId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_ACTIVITY.ATV_CUST_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String atvCustNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_ACTIVITY.ATV_CUST_NAME
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String atvCustName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_ACTIVITY.ATV_DATE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private Date atvDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_ACTIVITY.ATV_PLACE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String atvPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_ACTIVITY.ATV_TITLE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String atvTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_ACTIVITY.ATV_DESC
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String atvDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_ACTIVITY.ATV_ID
     *
     * @return the value of CST_ACTIVITY.ATV_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public BigDecimal getAtvId() {
        return atvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_ACTIVITY.ATV_ID
     *
     * @param atvId the value for CST_ACTIVITY.ATV_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setAtvId(BigDecimal atvId) {
        this.atvId = atvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_ACTIVITY.ATV_CUST_NO
     *
     * @return the value of CST_ACTIVITY.ATV_CUST_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getAtvCustNo() {
        return atvCustNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_ACTIVITY.ATV_CUST_NO
     *
     * @param atvCustNo the value for CST_ACTIVITY.ATV_CUST_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setAtvCustNo(String atvCustNo) {
        this.atvCustNo = atvCustNo == null ? null : atvCustNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_ACTIVITY.ATV_CUST_NAME
     *
     * @return the value of CST_ACTIVITY.ATV_CUST_NAME
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getAtvCustName() {
        return atvCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_ACTIVITY.ATV_CUST_NAME
     *
     * @param atvCustName the value for CST_ACTIVITY.ATV_CUST_NAME
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setAtvCustName(String atvCustName) {
        this.atvCustName = atvCustName == null ? null : atvCustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_ACTIVITY.ATV_DATE
     *
     * @return the value of CST_ACTIVITY.ATV_DATE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public Date getAtvDate() {
        return atvDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_ACTIVITY.ATV_DATE
     *
     * @param atvDate the value for CST_ACTIVITY.ATV_DATE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setAtvDate(Date atvDate) {
        this.atvDate = atvDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_ACTIVITY.ATV_PLACE
     *
     * @return the value of CST_ACTIVITY.ATV_PLACE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getAtvPlace() {
        return atvPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_ACTIVITY.ATV_PLACE
     *
     * @param atvPlace the value for CST_ACTIVITY.ATV_PLACE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setAtvPlace(String atvPlace) {
        this.atvPlace = atvPlace == null ? null : atvPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_ACTIVITY.ATV_TITLE
     *
     * @return the value of CST_ACTIVITY.ATV_TITLE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getAtvTitle() {
        return atvTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_ACTIVITY.ATV_TITLE
     *
     * @param atvTitle the value for CST_ACTIVITY.ATV_TITLE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setAtvTitle(String atvTitle) {
        this.atvTitle = atvTitle == null ? null : atvTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_ACTIVITY.ATV_DESC
     *
     * @return the value of CST_ACTIVITY.ATV_DESC
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getAtvDesc() {
        return atvDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_ACTIVITY.ATV_DESC
     *
     * @param atvDesc the value for CST_ACTIVITY.ATV_DESC
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setAtvDesc(String atvDesc) {
        this.atvDesc = atvDesc == null ? null : atvDesc.trim();
    }
}