package com.crm.entity;

import java.math.BigDecimal;

public class CstCustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_NAME
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_REGION
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_MANAGER_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private BigDecimal custManagerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_MANAGER_NAME
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custManagerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_LEVEL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private BigDecimal custLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_LEVEL_LABEL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custLevelLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_SATISFY
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private BigDecimal custSatisfy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_CREDIT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private BigDecimal custCredit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_ZIP
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custZip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_TEL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_FAX
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custFax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_WEBSITE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custWebsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_LICENCE_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custLicenceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_CHIEFTAIN
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custChieftain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_BANKROLL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private BigDecimal custBankroll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_TURNOVER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private BigDecimal custTurnover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_BANK
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custBank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_BANK_ACCOUNT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custBankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_LOCAL_TAX_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custLocalTaxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_NATIONAL_TAX_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custNationalTaxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_STATUS
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_CUSTOMER.CUST_ADDR
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String custAddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_NO
     *
     * @return the value of CST_CUSTOMER.CUST_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_NO
     *
     * @param custNo the value for CST_CUSTOMER.CUST_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_NAME
     *
     * @return the value of CST_CUSTOMER.CUST_NAME
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_NAME
     *
     * @param custName the value for CST_CUSTOMER.CUST_NAME
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_REGION
     *
     * @return the value of CST_CUSTOMER.CUST_REGION
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustRegion() {
        return custRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_REGION
     *
     * @param custRegion the value for CST_CUSTOMER.CUST_REGION
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustRegion(String custRegion) {
        this.custRegion = custRegion == null ? null : custRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_MANAGER_ID
     *
     * @return the value of CST_CUSTOMER.CUST_MANAGER_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public BigDecimal getCustManagerId() {
        return custManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_MANAGER_ID
     *
     * @param custManagerId the value for CST_CUSTOMER.CUST_MANAGER_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustManagerId(BigDecimal custManagerId) {
        this.custManagerId = custManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_MANAGER_NAME
     *
     * @return the value of CST_CUSTOMER.CUST_MANAGER_NAME
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustManagerName() {
        return custManagerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_MANAGER_NAME
     *
     * @param custManagerName the value for CST_CUSTOMER.CUST_MANAGER_NAME
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustManagerName(String custManagerName) {
        this.custManagerName = custManagerName == null ? null : custManagerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_LEVEL
     *
     * @return the value of CST_CUSTOMER.CUST_LEVEL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public BigDecimal getCustLevel() {
        return custLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_LEVEL
     *
     * @param custLevel the value for CST_CUSTOMER.CUST_LEVEL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustLevel(BigDecimal custLevel) {
        this.custLevel = custLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_LEVEL_LABEL
     *
     * @return the value of CST_CUSTOMER.CUST_LEVEL_LABEL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustLevelLabel() {
        return custLevelLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_LEVEL_LABEL
     *
     * @param custLevelLabel the value for CST_CUSTOMER.CUST_LEVEL_LABEL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustLevelLabel(String custLevelLabel) {
        this.custLevelLabel = custLevelLabel == null ? null : custLevelLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_SATISFY
     *
     * @return the value of CST_CUSTOMER.CUST_SATISFY
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public BigDecimal getCustSatisfy() {
        return custSatisfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_SATISFY
     *
     * @param custSatisfy the value for CST_CUSTOMER.CUST_SATISFY
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustSatisfy(BigDecimal custSatisfy) {
        this.custSatisfy = custSatisfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_CREDIT
     *
     * @return the value of CST_CUSTOMER.CUST_CREDIT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public BigDecimal getCustCredit() {
        return custCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_CREDIT
     *
     * @param custCredit the value for CST_CUSTOMER.CUST_CREDIT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustCredit(BigDecimal custCredit) {
        this.custCredit = custCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_ZIP
     *
     * @return the value of CST_CUSTOMER.CUST_ZIP
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustZip() {
        return custZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_ZIP
     *
     * @param custZip the value for CST_CUSTOMER.CUST_ZIP
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustZip(String custZip) {
        this.custZip = custZip == null ? null : custZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_TEL
     *
     * @return the value of CST_CUSTOMER.CUST_TEL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustTel() {
        return custTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_TEL
     *
     * @param custTel the value for CST_CUSTOMER.CUST_TEL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustTel(String custTel) {
        this.custTel = custTel == null ? null : custTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_FAX
     *
     * @return the value of CST_CUSTOMER.CUST_FAX
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustFax() {
        return custFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_FAX
     *
     * @param custFax the value for CST_CUSTOMER.CUST_FAX
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustFax(String custFax) {
        this.custFax = custFax == null ? null : custFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_WEBSITE
     *
     * @return the value of CST_CUSTOMER.CUST_WEBSITE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustWebsite() {
        return custWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_WEBSITE
     *
     * @param custWebsite the value for CST_CUSTOMER.CUST_WEBSITE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustWebsite(String custWebsite) {
        this.custWebsite = custWebsite == null ? null : custWebsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_LICENCE_NO
     *
     * @return the value of CST_CUSTOMER.CUST_LICENCE_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustLicenceNo() {
        return custLicenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_LICENCE_NO
     *
     * @param custLicenceNo the value for CST_CUSTOMER.CUST_LICENCE_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustLicenceNo(String custLicenceNo) {
        this.custLicenceNo = custLicenceNo == null ? null : custLicenceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_CHIEFTAIN
     *
     * @return the value of CST_CUSTOMER.CUST_CHIEFTAIN
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustChieftain() {
        return custChieftain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_CHIEFTAIN
     *
     * @param custChieftain the value for CST_CUSTOMER.CUST_CHIEFTAIN
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustChieftain(String custChieftain) {
        this.custChieftain = custChieftain == null ? null : custChieftain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_BANKROLL
     *
     * @return the value of CST_CUSTOMER.CUST_BANKROLL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public BigDecimal getCustBankroll() {
        return custBankroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_BANKROLL
     *
     * @param custBankroll the value for CST_CUSTOMER.CUST_BANKROLL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustBankroll(BigDecimal custBankroll) {
        this.custBankroll = custBankroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_TURNOVER
     *
     * @return the value of CST_CUSTOMER.CUST_TURNOVER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public BigDecimal getCustTurnover() {
        return custTurnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_TURNOVER
     *
     * @param custTurnover the value for CST_CUSTOMER.CUST_TURNOVER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustTurnover(BigDecimal custTurnover) {
        this.custTurnover = custTurnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_BANK
     *
     * @return the value of CST_CUSTOMER.CUST_BANK
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustBank() {
        return custBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_BANK
     *
     * @param custBank the value for CST_CUSTOMER.CUST_BANK
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustBank(String custBank) {
        this.custBank = custBank == null ? null : custBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_BANK_ACCOUNT
     *
     * @return the value of CST_CUSTOMER.CUST_BANK_ACCOUNT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustBankAccount() {
        return custBankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_BANK_ACCOUNT
     *
     * @param custBankAccount the value for CST_CUSTOMER.CUST_BANK_ACCOUNT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustBankAccount(String custBankAccount) {
        this.custBankAccount = custBankAccount == null ? null : custBankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_LOCAL_TAX_NO
     *
     * @return the value of CST_CUSTOMER.CUST_LOCAL_TAX_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustLocalTaxNo() {
        return custLocalTaxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_LOCAL_TAX_NO
     *
     * @param custLocalTaxNo the value for CST_CUSTOMER.CUST_LOCAL_TAX_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustLocalTaxNo(String custLocalTaxNo) {
        this.custLocalTaxNo = custLocalTaxNo == null ? null : custLocalTaxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_NATIONAL_TAX_NO
     *
     * @return the value of CST_CUSTOMER.CUST_NATIONAL_TAX_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustNationalTaxNo() {
        return custNationalTaxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_NATIONAL_TAX_NO
     *
     * @param custNationalTaxNo the value for CST_CUSTOMER.CUST_NATIONAL_TAX_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustNationalTaxNo(String custNationalTaxNo) {
        this.custNationalTaxNo = custNationalTaxNo == null ? null : custNationalTaxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_STATUS
     *
     * @return the value of CST_CUSTOMER.CUST_STATUS
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustStatus() {
        return custStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_STATUS
     *
     * @param custStatus the value for CST_CUSTOMER.CUST_STATUS
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustStatus(String custStatus) {
        this.custStatus = custStatus == null ? null : custStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_CUSTOMER.CUST_ADDR
     *
     * @return the value of CST_CUSTOMER.CUST_ADDR
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getCustAddr() {
        return custAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_CUSTOMER.CUST_ADDR
     *
     * @param custAddr the value for CST_CUSTOMER.CUST_ADDR
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setCustAddr(String custAddr) {
        this.custAddr = custAddr == null ? null : custAddr.trim();
    }
}