package com.crm.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CstLost {
    /**
     *
     * 丢失客户表内标识
     */
    private BigDecimal lstId;

    /**
     *
     * 客户标识
     */
    private String lstCustNo;

    /**
     *
     * 客户姓名
     */
    private String lstCustName;

    /**
     *
     * 客户管理人ID
     */
    private BigDecimal lstCustManagerId;

    /**
     *
     * 客户管理人姓名
     */
    private String lstCustManagerName;

    /**
     *
     * 上一次交易日期
     */
    private Date lstLastOrderDate;

    /**
     *
     * 确认丢失日期
     */
    private Date lstLostDate;

    /**
     *
     * 延缓丢失解决方案
     */
    private String lstDelay;

    /**
     *
     * 丢失客户原因
     */
    private String lstReason;

    /**
     *
     * 丢失客户状态标识
     */
    private String lstStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LOST.LST_ID
     *
     * @return the value of CST_LOST.LST_ID
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public BigDecimal getLstId() {
        return lstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LOST.LST_ID
     *
     * @param lstId the value for CST_LOST.LST_ID
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public void setLstId(BigDecimal lstId) {
        this.lstId = lstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LOST.LST_CUST_NO
     *
     * @return the value of CST_LOST.LST_CUST_NO
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public String getLstCustNo() {
        return lstCustNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LOST.LST_CUST_NO
     *
     * @param lstCustNo the value for CST_LOST.LST_CUST_NO
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public void setLstCustNo(String lstCustNo) {
        this.lstCustNo = lstCustNo == null ? null : lstCustNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LOST.LST_CUST_NAME
     *
     * @return the value of CST_LOST.LST_CUST_NAME
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public String getLstCustName() {
        return lstCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LOST.LST_CUST_NAME
     *
     * @param lstCustName the value for CST_LOST.LST_CUST_NAME
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public void setLstCustName(String lstCustName) {
        this.lstCustName = lstCustName == null ? null : lstCustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LOST.LST_CUST_MANAGER_ID
     *
     * @return the value of CST_LOST.LST_CUST_MANAGER_ID
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public BigDecimal getLstCustManagerId() {
        return lstCustManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LOST.LST_CUST_MANAGER_ID
     *
     * @param lstCustManagerId the value for CST_LOST.LST_CUST_MANAGER_ID
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public void setLstCustManagerId(BigDecimal lstCustManagerId) {
        this.lstCustManagerId = lstCustManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LOST.LST_CUST_MANAGER_NAME
     *
     * @return the value of CST_LOST.LST_CUST_MANAGER_NAME
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public String getLstCustManagerName() {
        return lstCustManagerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LOST.LST_CUST_MANAGER_NAME
     *
     * @param lstCustManagerName the value for CST_LOST.LST_CUST_MANAGER_NAME
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public void setLstCustManagerName(String lstCustManagerName) {
        this.lstCustManagerName = lstCustManagerName == null ? null : lstCustManagerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LOST.LST_LAST_ORDER_DATE
     *
     * @return the value of CST_LOST.LST_LAST_ORDER_DATE
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public Date getLstLastOrderDate() {
        return lstLastOrderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LOST.LST_LAST_ORDER_DATE
     *
     * @param lstLastOrderDate the value for CST_LOST.LST_LAST_ORDER_DATE
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public void setLstLastOrderDate(Date lstLastOrderDate) {
        this.lstLastOrderDate = lstLastOrderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LOST.LST_LOST_DATE
     *
     * @return the value of CST_LOST.LST_LOST_DATE
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public Date getLstLostDate() {
        return lstLostDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LOST.LST_LOST_DATE
     *
     * @param lstLostDate the value for CST_LOST.LST_LOST_DATE
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public void setLstLostDate(Date lstLostDate) {
        this.lstLostDate = lstLostDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LOST.LST_DELAY
     *
     * @return the value of CST_LOST.LST_DELAY
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public String getLstDelay() {
        return lstDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LOST.LST_DELAY
     *
     * @param lstDelay the value for CST_LOST.LST_DELAY
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public void setLstDelay(String lstDelay) {
        this.lstDelay = lstDelay == null ? null : lstDelay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LOST.LST_REASON
     *
     * @return the value of CST_LOST.LST_REASON
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public String getLstReason() {
        return lstReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LOST.LST_REASON
     *
     * @param lstReason the value for CST_LOST.LST_REASON
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public void setLstReason(String lstReason) {
        this.lstReason = lstReason == null ? null : lstReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LOST.LST_STATUS
     *
     * @return the value of CST_LOST.LST_STATUS
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public String getLstStatus() {
        return lstStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LOST.LST_STATUS
     *
     * @param lstStatus the value for CST_LOST.LST_STATUS
     *
     * @mbg.generated Tue Aug 29 15:18:52 CST 2017
     */
    public void setLstStatus(String lstStatus) {
        this.lstStatus = lstStatus == null ? null : lstStatus.trim();
    }
}