package com.crm.entity;

public class CstLinkman {
    /**
     *
     * 客户联系人唯一标识
     */
    private Integer lkmId;

    /**
     *
     * 联系人所属客户唯一标识
     */
    private String lkmCustNo;

    /**
     *
     * 联系人所属客户姓名
     */
    private String lkmCustName;

    /**
     *
     * 联系人姓名
     */
    private String lkmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LINKMAN.LKM_SEX
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String lkmSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LINKMAN.LKM_POSTION
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String lkmPostion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LINKMAN.LKM_TEL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String lkmTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LINKMAN.LKM_MOBILE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String lkmMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LINKMAN.LKM_MEMO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String lkmMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_ID
     *
     * @return the value of CST_LINKMAN.LKM_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public Integer getLkmId() {
        return lkmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_ID
     *
     * @param lkmId the value for CST_LINKMAN.LKM_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setLkmId(Integer lkmId) {
        this.lkmId = lkmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_CUST_NO
     *
     * @return the value of CST_LINKMAN.LKM_CUST_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getLkmCustNo() {
        return lkmCustNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_CUST_NO
     *
     * @param lkmCustNo the value for CST_LINKMAN.LKM_CUST_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setLkmCustNo(String lkmCustNo) {
        this.lkmCustNo = lkmCustNo == null ? null : lkmCustNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_CUST_NAME
     *
     * @return the value of CST_LINKMAN.LKM_CUST_NAME
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getLkmCustName() {
        return lkmCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_CUST_NAME
     *
     * @param lkmCustName the value for CST_LINKMAN.LKM_CUST_NAME
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setLkmCustName(String lkmCustName) {
        this.lkmCustName = lkmCustName == null ? null : lkmCustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_NAME
     *
     * @return the value of CST_LINKMAN.LKM_NAME
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getLkmName() {
        return lkmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_NAME
     *
     * @param lkmName the value for CST_LINKMAN.LKM_NAME
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setLkmName(String lkmName) {
        this.lkmName = lkmName == null ? null : lkmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_SEX
     *
     * @return the value of CST_LINKMAN.LKM_SEX
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getLkmSex() {
        return lkmSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_SEX
     *
     * @param lkmSex the value for CST_LINKMAN.LKM_SEX
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setLkmSex(String lkmSex) {
        this.lkmSex = lkmSex == null ? null : lkmSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_POSTION
     *
     * @return the value of CST_LINKMAN.LKM_POSTION
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getLkmPostion() {
        return lkmPostion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_POSTION
     *
     * @param lkmPostion the value for CST_LINKMAN.LKM_POSTION
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setLkmPostion(String lkmPostion) {
        this.lkmPostion = lkmPostion == null ? null : lkmPostion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_TEL
     *
     * @return the value of CST_LINKMAN.LKM_TEL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getLkmTel() {
        return lkmTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_TEL
     *
     * @param lkmTel the value for CST_LINKMAN.LKM_TEL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setLkmTel(String lkmTel) {
        this.lkmTel = lkmTel == null ? null : lkmTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_MOBILE
     *
     * @return the value of CST_LINKMAN.LKM_MOBILE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getLkmMobile() {
        return lkmMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_MOBILE
     *
     * @param lkmMobile the value for CST_LINKMAN.LKM_MOBILE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setLkmMobile(String lkmMobile) {
        this.lkmMobile = lkmMobile == null ? null : lkmMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LINKMAN.LKM_MEMO
     *
     * @return the value of CST_LINKMAN.LKM_MEMO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getLkmMemo() {
        return lkmMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LINKMAN.LKM_MEMO
     *
     * @param lkmMemo the value for CST_LINKMAN.LKM_MEMO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setLkmMemo(String lkmMemo) {
        this.lkmMemo = lkmMemo == null ? null : lkmMemo.trim();
    }
}