package com.crm.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CstService {
    /**
     *
     * 服务的唯一编号
     */
    private BigDecimal svrId;

    /**
     *
     * 服务类型
     */
    private String svrType;

    /**
     *
     * 服务概要
     */
    private String svrTitle;

    /**
     *
     * 客户编码外键
     */
    private String svrCustNo;

    /**
     *
     * 客户名称
     */
    private String svrCustName;

    /**
     *
     *  服务状态
     */
    private String svrStatus;

    /**
     *
     * 详细描述
     */
    private String svrRequest;

    /**
     *
     * 服务创建人的编号
     */
    private BigDecimal svrCreateId;

    /**
     *
     * 服务创建人
     */
    private String svrCreateBy;

    /**
     *
     * 服务创建时间
     */
    private Date svrCreateDate;

    /**
     *
     * 经理编号
     */
    private BigDecimal svrDueId;

    /**
     *
     * 分配服务给经理
     */
    private String svrDueTo;

    /**
     *
     * 分配时间
     */
    private Date svrDueDate;

    /**
     *
     * 处理方法
     */
    private String svrDeal;

    /**
     *
     * 处理人的编号
     */
    private BigDecimal svrDealId;

    /**
     *
     * 处理人
     */
    private String svrDealBy;

    /**
     *
     * 处理时间
     */
    private Date svrDealDate;

    /**
     *
     * 处理结果
     */
    private String svrResult;

    /**
     *
     * 客户满意度
     */
    private Long svrSatisfy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_ID
     *
     * @return the value of CST_SERVICE.SVR_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public BigDecimal getSvrId() {
        return svrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_ID
     *
     * @param svrId the value for CST_SERVICE.SVR_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrId(BigDecimal svrId) {
        this.svrId = svrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_TYPE
     *
     * @return the value of CST_SERVICE.SVR_TYPE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getSvrType() {
        return svrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_TYPE
     *
     * @param svrType the value for CST_SERVICE.SVR_TYPE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrType(String svrType) {
        this.svrType = svrType == null ? null : svrType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_TITLE
     *
     * @return the value of CST_SERVICE.SVR_TITLE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getSvrTitle() {
        return svrTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_TITLE
     *
     * @param svrTitle the value for CST_SERVICE.SVR_TITLE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrTitle(String svrTitle) {
        this.svrTitle = svrTitle == null ? null : svrTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_CUST_NO
     *
     * @return the value of CST_SERVICE.SVR_CUST_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getSvrCustNo() {
        return svrCustNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_CUST_NO
     *
     * @param svrCustNo the value for CST_SERVICE.SVR_CUST_NO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrCustNo(String svrCustNo) {
        this.svrCustNo = svrCustNo == null ? null : svrCustNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_CUST_NAME
     *
     * @return the value of CST_SERVICE.SVR_CUST_NAME
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getSvrCustName() {
        return svrCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_CUST_NAME
     *
     * @param svrCustName the value for CST_SERVICE.SVR_CUST_NAME
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrCustName(String svrCustName) {
        this.svrCustName = svrCustName == null ? null : svrCustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_STATUS
     *
     * @return the value of CST_SERVICE.SVR_STATUS
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getSvrStatus() {
        return svrStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_STATUS
     *
     * @param svrStatus the value for CST_SERVICE.SVR_STATUS
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrStatus(String svrStatus) {
        this.svrStatus = svrStatus == null ? null : svrStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_REQUEST
     *
     * @return the value of CST_SERVICE.SVR_REQUEST
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getSvrRequest() {
        return svrRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_REQUEST
     *
     * @param svrRequest the value for CST_SERVICE.SVR_REQUEST
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrRequest(String svrRequest) {
        this.svrRequest = svrRequest == null ? null : svrRequest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_CREATE_ID
     *
     * @return the value of CST_SERVICE.SVR_CREATE_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public BigDecimal getSvrCreateId() {
        return svrCreateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_CREATE_ID
     *
     * @param svrCreateId the value for CST_SERVICE.SVR_CREATE_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrCreateId(BigDecimal svrCreateId) {
        this.svrCreateId = svrCreateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_CREATE_BY
     *
     * @return the value of CST_SERVICE.SVR_CREATE_BY
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getSvrCreateBy() {
        return svrCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_CREATE_BY
     *
     * @param svrCreateBy the value for CST_SERVICE.SVR_CREATE_BY
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrCreateBy(String svrCreateBy) {
        this.svrCreateBy = svrCreateBy == null ? null : svrCreateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_CREATE_DATE
     *
     * @return the value of CST_SERVICE.SVR_CREATE_DATE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public Date getSvrCreateDate() {
        return svrCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_CREATE_DATE
     *
     * @param svrCreateDate the value for CST_SERVICE.SVR_CREATE_DATE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrCreateDate(Date svrCreateDate) {
        this.svrCreateDate = svrCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_DUE_ID
     *
     * @return the value of CST_SERVICE.SVR_DUE_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public BigDecimal getSvrDueId() {
        return svrDueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_DUE_ID
     *
     * @param svrDueId the value for CST_SERVICE.SVR_DUE_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrDueId(BigDecimal svrDueId) {
        this.svrDueId = svrDueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_DUE_TO
     *
     * @return the value of CST_SERVICE.SVR_DUE_TO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getSvrDueTo() {
        return svrDueTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_DUE_TO
     *
     * @param svrDueTo the value for CST_SERVICE.SVR_DUE_TO
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrDueTo(String svrDueTo) {
        this.svrDueTo = svrDueTo == null ? null : svrDueTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_DUE_DATE
     *
     * @return the value of CST_SERVICE.SVR_DUE_DATE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public Date getSvrDueDate() {
        return svrDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_DUE_DATE
     *
     * @param svrDueDate the value for CST_SERVICE.SVR_DUE_DATE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrDueDate(Date svrDueDate) {
        this.svrDueDate = svrDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_DEAL
     *
     * @return the value of CST_SERVICE.SVR_DEAL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getSvrDeal() {
        return svrDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_DEAL
     *
     * @param svrDeal the value for CST_SERVICE.SVR_DEAL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrDeal(String svrDeal) {
        this.svrDeal = svrDeal == null ? null : svrDeal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_DEAL_ID
     *
     * @return the value of CST_SERVICE.SVR_DEAL_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public BigDecimal getSvrDealId() {
        return svrDealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_DEAL_ID
     *
     * @param svrDealId the value for CST_SERVICE.SVR_DEAL_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrDealId(BigDecimal svrDealId) {
        this.svrDealId = svrDealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_DEAL_BY
     *
     * @return the value of CST_SERVICE.SVR_DEAL_BY
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getSvrDealBy() {
        return svrDealBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_DEAL_BY
     *
     * @param svrDealBy the value for CST_SERVICE.SVR_DEAL_BY
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrDealBy(String svrDealBy) {
        this.svrDealBy = svrDealBy == null ? null : svrDealBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_DEAL_DATE
     *
     * @return the value of CST_SERVICE.SVR_DEAL_DATE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public Date getSvrDealDate() {
        return svrDealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_DEAL_DATE
     *
     * @param svrDealDate the value for CST_SERVICE.SVR_DEAL_DATE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrDealDate(Date svrDealDate) {
        this.svrDealDate = svrDealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_RESULT
     *
     * @return the value of CST_SERVICE.SVR_RESULT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getSvrResult() {
        return svrResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_RESULT
     *
     * @param svrResult the value for CST_SERVICE.SVR_RESULT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrResult(String svrResult) {
        this.svrResult = svrResult == null ? null : svrResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_SERVICE.SVR_SATISFY
     *
     * @return the value of CST_SERVICE.SVR_SATISFY
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public Long getSvrSatisfy() {
        return svrSatisfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_SERVICE.SVR_SATISFY
     *
     * @param svrSatisfy the value for CST_SERVICE.SVR_SATISFY
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setSvrSatisfy(Long svrSatisfy) {
        this.svrSatisfy = svrSatisfy;
    }
}