package com.crm.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class SysRoleRightExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public SysRoleRightExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRfIdIsNull() {
            addCriterion("RF_ID is null");
            return (Criteria) this;
        }

        public Criteria andRfIdIsNotNull() {
            addCriterion("RF_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRfIdEqualTo(BigDecimal value) {
            addCriterion("RF_ID =", value, "rfId");
            return (Criteria) this;
        }

        public Criteria andRfIdNotEqualTo(BigDecimal value) {
            addCriterion("RF_ID <>", value, "rfId");
            return (Criteria) this;
        }

        public Criteria andRfIdGreaterThan(BigDecimal value) {
            addCriterion("RF_ID >", value, "rfId");
            return (Criteria) this;
        }

        public Criteria andRfIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RF_ID >=", value, "rfId");
            return (Criteria) this;
        }

        public Criteria andRfIdLessThan(BigDecimal value) {
            addCriterion("RF_ID <", value, "rfId");
            return (Criteria) this;
        }

        public Criteria andRfIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RF_ID <=", value, "rfId");
            return (Criteria) this;
        }

        public Criteria andRfIdIn(List<BigDecimal> values) {
            addCriterion("RF_ID in", values, "rfId");
            return (Criteria) this;
        }

        public Criteria andRfIdNotIn(List<BigDecimal> values) {
            addCriterion("RF_ID not in", values, "rfId");
            return (Criteria) this;
        }

        public Criteria andRfIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RF_ID between", value1, value2, "rfId");
            return (Criteria) this;
        }

        public Criteria andRfIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RF_ID not between", value1, value2, "rfId");
            return (Criteria) this;
        }

        public Criteria andRfRoleIdIsNull() {
            addCriterion("RF_ROLE_ID is null");
            return (Criteria) this;
        }

        public Criteria andRfRoleIdIsNotNull() {
            addCriterion("RF_ROLE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRfRoleIdEqualTo(BigDecimal value) {
            addCriterion("RF_ROLE_ID =", value, "rfRoleId");
            return (Criteria) this;
        }

        public Criteria andRfRoleIdNotEqualTo(BigDecimal value) {
            addCriterion("RF_ROLE_ID <>", value, "rfRoleId");
            return (Criteria) this;
        }

        public Criteria andRfRoleIdGreaterThan(BigDecimal value) {
            addCriterion("RF_ROLE_ID >", value, "rfRoleId");
            return (Criteria) this;
        }

        public Criteria andRfRoleIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RF_ROLE_ID >=", value, "rfRoleId");
            return (Criteria) this;
        }

        public Criteria andRfRoleIdLessThan(BigDecimal value) {
            addCriterion("RF_ROLE_ID <", value, "rfRoleId");
            return (Criteria) this;
        }

        public Criteria andRfRoleIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RF_ROLE_ID <=", value, "rfRoleId");
            return (Criteria) this;
        }

        public Criteria andRfRoleIdIn(List<BigDecimal> values) {
            addCriterion("RF_ROLE_ID in", values, "rfRoleId");
            return (Criteria) this;
        }

        public Criteria andRfRoleIdNotIn(List<BigDecimal> values) {
            addCriterion("RF_ROLE_ID not in", values, "rfRoleId");
            return (Criteria) this;
        }

        public Criteria andRfRoleIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RF_ROLE_ID between", value1, value2, "rfRoleId");
            return (Criteria) this;
        }

        public Criteria andRfRoleIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RF_ROLE_ID not between", value1, value2, "rfRoleId");
            return (Criteria) this;
        }

        public Criteria andRfRightCodeIsNull() {
            addCriterion("RF_RIGHT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andRfRightCodeIsNotNull() {
            addCriterion("RF_RIGHT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andRfRightCodeEqualTo(String value) {
            addCriterion("RF_RIGHT_CODE =", value, "rfRightCode");
            return (Criteria) this;
        }

        public Criteria andRfRightCodeNotEqualTo(String value) {
            addCriterion("RF_RIGHT_CODE <>", value, "rfRightCode");
            return (Criteria) this;
        }

        public Criteria andRfRightCodeGreaterThan(String value) {
            addCriterion("RF_RIGHT_CODE >", value, "rfRightCode");
            return (Criteria) this;
        }

        public Criteria andRfRightCodeGreaterThanOrEqualTo(String value) {
            addCriterion("RF_RIGHT_CODE >=", value, "rfRightCode");
            return (Criteria) this;
        }

        public Criteria andRfRightCodeLessThan(String value) {
            addCriterion("RF_RIGHT_CODE <", value, "rfRightCode");
            return (Criteria) this;
        }

        public Criteria andRfRightCodeLessThanOrEqualTo(String value) {
            addCriterion("RF_RIGHT_CODE <=", value, "rfRightCode");
            return (Criteria) this;
        }

        public Criteria andRfRightCodeLike(String value) {
            addCriterion("RF_RIGHT_CODE like", value, "rfRightCode");
            return (Criteria) this;
        }

        public Criteria andRfRightCodeNotLike(String value) {
            addCriterion("RF_RIGHT_CODE not like", value, "rfRightCode");
            return (Criteria) this;
        }

        public Criteria andRfRightCodeIn(List<String> values) {
            addCriterion("RF_RIGHT_CODE in", values, "rfRightCode");
            return (Criteria) this;
        }

        public Criteria andRfRightCodeNotIn(List<String> values) {
            addCriterion("RF_RIGHT_CODE not in", values, "rfRightCode");
            return (Criteria) this;
        }

        public Criteria andRfRightCodeBetween(String value1, String value2) {
            addCriterion("RF_RIGHT_CODE between", value1, value2, "rfRightCode");
            return (Criteria) this;
        }

        public Criteria andRfRightCodeNotBetween(String value1, String value2) {
            addCriterion("RF_RIGHT_CODE not between", value1, value2, "rfRightCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 29 10:30:00 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}