package com.crm.entity;

import java.util.ArrayList;
import java.util.List;

public class SysRight {
    /**
     *
     * 
     * 
     *Ȩ�ޱ���
     *
     */
    private String rightCode;

    /**
     *
     * 
     * 
     *
     *
     */
    private String rightParentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RIGHT.RIGHT_TYPE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String rightType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RIGHT.RIGHT_TEXT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String rightText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RIGHT.RIGHT_URL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String rightUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RIGHT.RIGHT_TIP
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String rightTip;
    
    /**
     * 
     */
    private List roleList=new ArrayList();
    

    public List getRoleList() {
		return roleList;
	}

	public void setRoleList(List roleList) {
		this.roleList = roleList;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RIGHT.RIGHT_CODE
     *
     * @return the value of SYS_RIGHT.RIGHT_CODE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getRightCode() {
        return rightCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RIGHT.RIGHT_CODE
     *
     * @param rightCode the value for SYS_RIGHT.RIGHT_CODE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setRightCode(String rightCode) {
        this.rightCode = rightCode == null ? null : rightCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RIGHT.RIGHT_PARENT_CODE
     *
     * @return the value of SYS_RIGHT.RIGHT_PARENT_CODE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getRightParentCode() {
        return rightParentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RIGHT.RIGHT_PARENT_CODE
     *
     * @param rightParentCode the value for SYS_RIGHT.RIGHT_PARENT_CODE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setRightParentCode(String rightParentCode) {
        this.rightParentCode = rightParentCode == null ? null : rightParentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RIGHT.RIGHT_TYPE
     *
     * @return the value of SYS_RIGHT.RIGHT_TYPE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getRightType() {
        return rightType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RIGHT.RIGHT_TYPE
     *
     * @param rightType the value for SYS_RIGHT.RIGHT_TYPE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setRightType(String rightType) {
        this.rightType = rightType == null ? null : rightType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RIGHT.RIGHT_TEXT
     *
     * @return the value of SYS_RIGHT.RIGHT_TEXT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getRightText() {
        return rightText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RIGHT.RIGHT_TEXT
     *
     * @param rightText the value for SYS_RIGHT.RIGHT_TEXT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setRightText(String rightText) {
        this.rightText = rightText == null ? null : rightText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RIGHT.RIGHT_URL
     *
     * @return the value of SYS_RIGHT.RIGHT_URL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getRightUrl() {
        return rightUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RIGHT.RIGHT_URL
     *
     * @param rightUrl the value for SYS_RIGHT.RIGHT_URL
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setRightUrl(String rightUrl) {
        this.rightUrl = rightUrl == null ? null : rightUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RIGHT.RIGHT_TIP
     *
     * @return the value of SYS_RIGHT.RIGHT_TIP
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getRightTip() {
        return rightTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RIGHT.RIGHT_TIP
     *
     * @param rightTip the value for SYS_RIGHT.RIGHT_TIP
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setRightTip(String rightTip) {
        this.rightTip = rightTip == null ? null : rightTip.trim();
    }

	@Override
	public String toString() {
		return "SysRight [rightCode=" + rightCode + ", rightParentCode=" + rightParentCode + ", rightType=" + rightType
				+ ", rightText=" + rightText + ", rightUrl=" + rightUrl + ", rightTip=" + rightTip + ", roleList="
				+ roleList + "]";
	}
    
    
}