package com.crm.entity;

import java.math.BigDecimal;

public class SysRoleRight {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_RIGHT.RF_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private BigDecimal rfId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_RIGHT.RF_ROLE_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private BigDecimal rfRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_RIGHT.RF_RIGHT_CODE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String rfRightCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_RIGHT.RF_ID
     *
     * @return the value of SYS_ROLE_RIGHT.RF_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public BigDecimal getRfId() {
        return rfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_RIGHT.RF_ID
     *
     * @param rfId the value for SYS_ROLE_RIGHT.RF_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setRfId(BigDecimal rfId) {
        this.rfId = rfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_RIGHT.RF_ROLE_ID
     *
     * @return the value of SYS_ROLE_RIGHT.RF_ROLE_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public BigDecimal getRfRoleId() {
        return rfRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_RIGHT.RF_ROLE_ID
     *
     * @param rfRoleId the value for SYS_ROLE_RIGHT.RF_ROLE_ID
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setRfRoleId(BigDecimal rfRoleId) {
        this.rfRoleId = rfRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_RIGHT.RF_RIGHT_CODE
     *
     * @return the value of SYS_ROLE_RIGHT.RF_RIGHT_CODE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getRfRightCode() {
        return rfRightCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_RIGHT.RF_RIGHT_CODE
     *
     * @param rfRightCode the value for SYS_ROLE_RIGHT.RF_RIGHT_CODE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setRfRightCode(String rfRightCode) {
        this.rfRightCode = rfRightCode == null ? null : rfRightCode.trim();
    }
}