package com.crm.mapper;

import com.crm.entity.CstCustomer;
import com.crm.entity.CstCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CstCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_CUSTOMER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    long countByExample(CstCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_CUSTOMER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int deleteByExample(CstCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_CUSTOMER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int deleteByPrimaryKey(String custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_CUSTOMER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int insert(CstCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_CUSTOMER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int insertSelective(CstCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_CUSTOMER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    List<CstCustomer> selectByExampleWithBLOBs(CstCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_CUSTOMER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    List<CstCustomer> selectByExample(CstCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_CUSTOMER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    CstCustomer selectByPrimaryKey(String custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_CUSTOMER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") CstCustomer record, @Param("example") CstCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_CUSTOMER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CstCustomer record, @Param("example") CstCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_CUSTOMER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByExample(@Param("record") CstCustomer record, @Param("example") CstCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_CUSTOMER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByPrimaryKeySelective(CstCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_CUSTOMER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CstCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_CUSTOMER
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByPrimaryKey(CstCustomer record);
    
    List<CstCustomer> likeByName(String name);
}