package com.crm.mapper;

import com.crm.entity.CstLost;
import com.crm.entity.CstLostExample;
import com.crm.entity.CstLostWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CstLostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    long countByExample(CstLostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int deleteByExample(CstLostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int deleteByPrimaryKey(Integer lstId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int insert(CstLostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int insertSelective(CstLostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    List<CstLostWithBLOBs> selectByExampleWithBLOBs(CstLostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    List<CstLost> selectByExample(CstLostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    CstLostWithBLOBs selectByPrimaryKey(Integer lstId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") CstLostWithBLOBs record, @Param("example") CstLostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CstLostWithBLOBs record, @Param("example") CstLostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByExample(@Param("record") CstLost record, @Param("example") CstLostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByPrimaryKeySelective(CstLostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CstLostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByPrimaryKey(CstLost record);
}