package com.crm.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.crm.entity.CstLost;
import com.crm.entity.CstLostExample;

public interface CstLostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 13:51:56 CST 2017
     */
    long countByExample(CstLostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 13:51:56 CST 2017
     */
    int deleteByExample(CstLostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 13:51:56 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal lstId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 13:51:56 CST 2017
     */
    int insert(CstLost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 13:51:56 CST 2017
     */
    int insertSelective(CstLost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 13:51:56 CST 2017
     */
    List<CstLost> selectByExample(CstLostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 13:51:56 CST 2017
     */
    CstLost selectByPrimaryKey(BigDecimal lstId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 13:51:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") CstLost record, @Param("example") CstLostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 13:51:56 CST 2017
     */
    int updateByExample(@Param("record") CstLost record, @Param("example") CstLostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 13:51:56 CST 2017
     */
    int updateByPrimaryKeySelective(CstLost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_LOST
     *
     * @mbg.generated Tue Aug 29 13:51:56 CST 2017
     */
    int updateByPrimaryKey(CstLost record);
}