package com.crm.mapper;

import com.crm.entity.SalPlan;
import com.crm.entity.SalPlanExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAL_PLAN
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    long countByExample(SalPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAL_PLAN
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int deleteByExample(SalPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAL_PLAN
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal plaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAL_PLAN
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int insert(SalPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAL_PLAN
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int insertSelective(SalPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAL_PLAN
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    List<SalPlan> selectByExample(SalPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAL_PLAN
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    SalPlan selectByPrimaryKey(BigDecimal plaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAL_PLAN
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") SalPlan record, @Param("example") SalPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAL_PLAN
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByExample(@Param("record") SalPlan record, @Param("example") SalPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAL_PLAN
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByPrimaryKeySelective(SalPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAL_PLAN
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByPrimaryKey(SalPlan record);
}