package com.crm.mapper;

import com.crm.entity.SysRoleRight;
import com.crm.entity.SysRoleRightExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleRightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    long countByExample(SysRoleRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int deleteByExample(SysRoleRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal rfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int insert(SysRoleRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int insertSelective(SysRoleRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    List<SysRoleRight> selectByExample(SysRoleRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    SysRoleRight selectByPrimaryKey(BigDecimal rfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysRoleRight record, @Param("example") SysRoleRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByExample(@Param("record") SysRoleRight record, @Param("example") SysRoleRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByPrimaryKeySelective(SysRoleRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByPrimaryKey(SysRoleRight record);
}