package com.crm.mapper;

import com.crm.entity.SysRight;
import com.crm.entity.SysRightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    long countByExample(SysRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int deleteByExample(SysRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int deleteByPrimaryKey(String rightCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int insert(SysRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int insertSelective(SysRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    List<SysRight> selectByExample(SysRightExample example);
    
    
    List selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    SysRight selectByPrimaryKey(String rightCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysRight record, @Param("example") SysRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByExample(@Param("record") SysRight record, @Param("example") SysRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByPrimaryKeySelective(SysRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RIGHT
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    int updateByPrimaryKey(SysRight record);
}