package com.crm.entity;

public class CstLostWithBLOBs extends CstLost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LOST.LST_DELAY
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String lstDelay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CST_LOST.LST_REASON
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    private String lstReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LOST.LST_DELAY
     *
     * @return the value of CST_LOST.LST_DELAY
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getLstDelay() {
        return lstDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LOST.LST_DELAY
     *
     * @param lstDelay the value for CST_LOST.LST_DELAY
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setLstDelay(String lstDelay) {
        this.lstDelay = lstDelay == null ? null : lstDelay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CST_LOST.LST_REASON
     *
     * @return the value of CST_LOST.LST_REASON
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getLstReason() {
        return lstReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CST_LOST.LST_REASON
     *
     * @param lstReason the value for CST_LOST.LST_REASON
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setLstReason(String lstReason) {
        this.lstReason = lstReason == null ? null : lstReason.trim();
    }
}