package com.crm.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CstServiceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public CstServiceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSvrIdIsNull() {
            addCriterion("SVR_ID is null");
            return (Criteria) this;
        }

        public Criteria andSvrIdIsNotNull() {
            addCriterion("SVR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSvrIdEqualTo(BigDecimal value) {
            addCriterion("SVR_ID =", value, "svrId");
            return (Criteria) this;
        }

        public Criteria andSvrIdNotEqualTo(BigDecimal value) {
            addCriterion("SVR_ID <>", value, "svrId");
            return (Criteria) this;
        }

        public Criteria andSvrIdGreaterThan(BigDecimal value) {
            addCriterion("SVR_ID >", value, "svrId");
            return (Criteria) this;
        }

        public Criteria andSvrIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SVR_ID >=", value, "svrId");
            return (Criteria) this;
        }

        public Criteria andSvrIdLessThan(BigDecimal value) {
            addCriterion("SVR_ID <", value, "svrId");
            return (Criteria) this;
        }

        public Criteria andSvrIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SVR_ID <=", value, "svrId");
            return (Criteria) this;
        }

        public Criteria andSvrIdIn(List<BigDecimal> values) {
            addCriterion("SVR_ID in", values, "svrId");
            return (Criteria) this;
        }

        public Criteria andSvrIdNotIn(List<BigDecimal> values) {
            addCriterion("SVR_ID not in", values, "svrId");
            return (Criteria) this;
        }

        public Criteria andSvrIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SVR_ID between", value1, value2, "svrId");
            return (Criteria) this;
        }

        public Criteria andSvrIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SVR_ID not between", value1, value2, "svrId");
            return (Criteria) this;
        }

        public Criteria andSvrTypeIsNull() {
            addCriterion("SVR_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSvrTypeIsNotNull() {
            addCriterion("SVR_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSvrTypeEqualTo(String value) {
            addCriterion("SVR_TYPE =", value, "svrType");
            return (Criteria) this;
        }

        public Criteria andSvrTypeNotEqualTo(String value) {
            addCriterion("SVR_TYPE <>", value, "svrType");
            return (Criteria) this;
        }

        public Criteria andSvrTypeGreaterThan(String value) {
            addCriterion("SVR_TYPE >", value, "svrType");
            return (Criteria) this;
        }

        public Criteria andSvrTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SVR_TYPE >=", value, "svrType");
            return (Criteria) this;
        }

        public Criteria andSvrTypeLessThan(String value) {
            addCriterion("SVR_TYPE <", value, "svrType");
            return (Criteria) this;
        }

        public Criteria andSvrTypeLessThanOrEqualTo(String value) {
            addCriterion("SVR_TYPE <=", value, "svrType");
            return (Criteria) this;
        }

        public Criteria andSvrTypeLike(String value) {
            addCriterion("SVR_TYPE like", value, "svrType");
            return (Criteria) this;
        }

        public Criteria andSvrTypeNotLike(String value) {
            addCriterion("SVR_TYPE not like", value, "svrType");
            return (Criteria) this;
        }

        public Criteria andSvrTypeIn(List<String> values) {
            addCriterion("SVR_TYPE in", values, "svrType");
            return (Criteria) this;
        }

        public Criteria andSvrTypeNotIn(List<String> values) {
            addCriterion("SVR_TYPE not in", values, "svrType");
            return (Criteria) this;
        }

        public Criteria andSvrTypeBetween(String value1, String value2) {
            addCriterion("SVR_TYPE between", value1, value2, "svrType");
            return (Criteria) this;
        }

        public Criteria andSvrTypeNotBetween(String value1, String value2) {
            addCriterion("SVR_TYPE not between", value1, value2, "svrType");
            return (Criteria) this;
        }

        public Criteria andSvrTitleIsNull() {
            addCriterion("SVR_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andSvrTitleIsNotNull() {
            addCriterion("SVR_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andSvrTitleEqualTo(String value) {
            addCriterion("SVR_TITLE =", value, "svrTitle");
            return (Criteria) this;
        }

        public Criteria andSvrTitleNotEqualTo(String value) {
            addCriterion("SVR_TITLE <>", value, "svrTitle");
            return (Criteria) this;
        }

        public Criteria andSvrTitleGreaterThan(String value) {
            addCriterion("SVR_TITLE >", value, "svrTitle");
            return (Criteria) this;
        }

        public Criteria andSvrTitleGreaterThanOrEqualTo(String value) {
            addCriterion("SVR_TITLE >=", value, "svrTitle");
            return (Criteria) this;
        }

        public Criteria andSvrTitleLessThan(String value) {
            addCriterion("SVR_TITLE <", value, "svrTitle");
            return (Criteria) this;
        }

        public Criteria andSvrTitleLessThanOrEqualTo(String value) {
            addCriterion("SVR_TITLE <=", value, "svrTitle");
            return (Criteria) this;
        }

        public Criteria andSvrTitleLike(String value) {
            addCriterion("SVR_TITLE like", value, "svrTitle");
            return (Criteria) this;
        }

        public Criteria andSvrTitleNotLike(String value) {
            addCriterion("SVR_TITLE not like", value, "svrTitle");
            return (Criteria) this;
        }

        public Criteria andSvrTitleIn(List<String> values) {
            addCriterion("SVR_TITLE in", values, "svrTitle");
            return (Criteria) this;
        }

        public Criteria andSvrTitleNotIn(List<String> values) {
            addCriterion("SVR_TITLE not in", values, "svrTitle");
            return (Criteria) this;
        }

        public Criteria andSvrTitleBetween(String value1, String value2) {
            addCriterion("SVR_TITLE between", value1, value2, "svrTitle");
            return (Criteria) this;
        }

        public Criteria andSvrTitleNotBetween(String value1, String value2) {
            addCriterion("SVR_TITLE not between", value1, value2, "svrTitle");
            return (Criteria) this;
        }

        public Criteria andSvrCustNoIsNull() {
            addCriterion("SVR_CUST_NO is null");
            return (Criteria) this;
        }

        public Criteria andSvrCustNoIsNotNull() {
            addCriterion("SVR_CUST_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSvrCustNoEqualTo(String value) {
            addCriterion("SVR_CUST_NO =", value, "svrCustNo");
            return (Criteria) this;
        }

        public Criteria andSvrCustNoNotEqualTo(String value) {
            addCriterion("SVR_CUST_NO <>", value, "svrCustNo");
            return (Criteria) this;
        }

        public Criteria andSvrCustNoGreaterThan(String value) {
            addCriterion("SVR_CUST_NO >", value, "svrCustNo");
            return (Criteria) this;
        }

        public Criteria andSvrCustNoGreaterThanOrEqualTo(String value) {
            addCriterion("SVR_CUST_NO >=", value, "svrCustNo");
            return (Criteria) this;
        }

        public Criteria andSvrCustNoLessThan(String value) {
            addCriterion("SVR_CUST_NO <", value, "svrCustNo");
            return (Criteria) this;
        }

        public Criteria andSvrCustNoLessThanOrEqualTo(String value) {
            addCriterion("SVR_CUST_NO <=", value, "svrCustNo");
            return (Criteria) this;
        }

        public Criteria andSvrCustNoLike(String value) {
            addCriterion("SVR_CUST_NO like", value, "svrCustNo");
            return (Criteria) this;
        }

        public Criteria andSvrCustNoNotLike(String value) {
            addCriterion("SVR_CUST_NO not like", value, "svrCustNo");
            return (Criteria) this;
        }

        public Criteria andSvrCustNoIn(List<String> values) {
            addCriterion("SVR_CUST_NO in", values, "svrCustNo");
            return (Criteria) this;
        }

        public Criteria andSvrCustNoNotIn(List<String> values) {
            addCriterion("SVR_CUST_NO not in", values, "svrCustNo");
            return (Criteria) this;
        }

        public Criteria andSvrCustNoBetween(String value1, String value2) {
            addCriterion("SVR_CUST_NO between", value1, value2, "svrCustNo");
            return (Criteria) this;
        }

        public Criteria andSvrCustNoNotBetween(String value1, String value2) {
            addCriterion("SVR_CUST_NO not between", value1, value2, "svrCustNo");
            return (Criteria) this;
        }

        public Criteria andSvrCustNameIsNull() {
            addCriterion("SVR_CUST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSvrCustNameIsNotNull() {
            addCriterion("SVR_CUST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSvrCustNameEqualTo(String value) {
            addCriterion("SVR_CUST_NAME =", value, "svrCustName");
            return (Criteria) this;
        }

        public Criteria andSvrCustNameNotEqualTo(String value) {
            addCriterion("SVR_CUST_NAME <>", value, "svrCustName");
            return (Criteria) this;
        }

        public Criteria andSvrCustNameGreaterThan(String value) {
            addCriterion("SVR_CUST_NAME >", value, "svrCustName");
            return (Criteria) this;
        }

        public Criteria andSvrCustNameGreaterThanOrEqualTo(String value) {
            addCriterion("SVR_CUST_NAME >=", value, "svrCustName");
            return (Criteria) this;
        }

        public Criteria andSvrCustNameLessThan(String value) {
            addCriterion("SVR_CUST_NAME <", value, "svrCustName");
            return (Criteria) this;
        }

        public Criteria andSvrCustNameLessThanOrEqualTo(String value) {
            addCriterion("SVR_CUST_NAME <=", value, "svrCustName");
            return (Criteria) this;
        }

        public Criteria andSvrCustNameLike(String value) {
            addCriterion("SVR_CUST_NAME like", value, "svrCustName");
            return (Criteria) this;
        }

        public Criteria andSvrCustNameNotLike(String value) {
            addCriterion("SVR_CUST_NAME not like", value, "svrCustName");
            return (Criteria) this;
        }

        public Criteria andSvrCustNameIn(List<String> values) {
            addCriterion("SVR_CUST_NAME in", values, "svrCustName");
            return (Criteria) this;
        }

        public Criteria andSvrCustNameNotIn(List<String> values) {
            addCriterion("SVR_CUST_NAME not in", values, "svrCustName");
            return (Criteria) this;
        }

        public Criteria andSvrCustNameBetween(String value1, String value2) {
            addCriterion("SVR_CUST_NAME between", value1, value2, "svrCustName");
            return (Criteria) this;
        }

        public Criteria andSvrCustNameNotBetween(String value1, String value2) {
            addCriterion("SVR_CUST_NAME not between", value1, value2, "svrCustName");
            return (Criteria) this;
        }

        public Criteria andSvrStatusIsNull() {
            addCriterion("SVR_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSvrStatusIsNotNull() {
            addCriterion("SVR_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSvrStatusEqualTo(String value) {
            addCriterion("SVR_STATUS =", value, "svrStatus");
            return (Criteria) this;
        }

        public Criteria andSvrStatusNotEqualTo(String value) {
            addCriterion("SVR_STATUS <>", value, "svrStatus");
            return (Criteria) this;
        }

        public Criteria andSvrStatusGreaterThan(String value) {
            addCriterion("SVR_STATUS >", value, "svrStatus");
            return (Criteria) this;
        }

        public Criteria andSvrStatusGreaterThanOrEqualTo(String value) {
            addCriterion("SVR_STATUS >=", value, "svrStatus");
            return (Criteria) this;
        }

        public Criteria andSvrStatusLessThan(String value) {
            addCriterion("SVR_STATUS <", value, "svrStatus");
            return (Criteria) this;
        }

        public Criteria andSvrStatusLessThanOrEqualTo(String value) {
            addCriterion("SVR_STATUS <=", value, "svrStatus");
            return (Criteria) this;
        }

        public Criteria andSvrStatusLike(String value) {
            addCriterion("SVR_STATUS like", value, "svrStatus");
            return (Criteria) this;
        }

        public Criteria andSvrStatusNotLike(String value) {
            addCriterion("SVR_STATUS not like", value, "svrStatus");
            return (Criteria) this;
        }

        public Criteria andSvrStatusIn(List<String> values) {
            addCriterion("SVR_STATUS in", values, "svrStatus");
            return (Criteria) this;
        }

        public Criteria andSvrStatusNotIn(List<String> values) {
            addCriterion("SVR_STATUS not in", values, "svrStatus");
            return (Criteria) this;
        }

        public Criteria andSvrStatusBetween(String value1, String value2) {
            addCriterion("SVR_STATUS between", value1, value2, "svrStatus");
            return (Criteria) this;
        }

        public Criteria andSvrStatusNotBetween(String value1, String value2) {
            addCriterion("SVR_STATUS not between", value1, value2, "svrStatus");
            return (Criteria) this;
        }

        public Criteria andSvrRequestIsNull() {
            addCriterion("SVR_REQUEST is null");
            return (Criteria) this;
        }

        public Criteria andSvrRequestIsNotNull() {
            addCriterion("SVR_REQUEST is not null");
            return (Criteria) this;
        }

        public Criteria andSvrRequestEqualTo(String value) {
            addCriterion("SVR_REQUEST =", value, "svrRequest");
            return (Criteria) this;
        }

        public Criteria andSvrRequestNotEqualTo(String value) {
            addCriterion("SVR_REQUEST <>", value, "svrRequest");
            return (Criteria) this;
        }

        public Criteria andSvrRequestGreaterThan(String value) {
            addCriterion("SVR_REQUEST >", value, "svrRequest");
            return (Criteria) this;
        }

        public Criteria andSvrRequestGreaterThanOrEqualTo(String value) {
            addCriterion("SVR_REQUEST >=", value, "svrRequest");
            return (Criteria) this;
        }

        public Criteria andSvrRequestLessThan(String value) {
            addCriterion("SVR_REQUEST <", value, "svrRequest");
            return (Criteria) this;
        }

        public Criteria andSvrRequestLessThanOrEqualTo(String value) {
            addCriterion("SVR_REQUEST <=", value, "svrRequest");
            return (Criteria) this;
        }

        public Criteria andSvrRequestLike(String value) {
            addCriterion("SVR_REQUEST like", value, "svrRequest");
            return (Criteria) this;
        }

        public Criteria andSvrRequestNotLike(String value) {
            addCriterion("SVR_REQUEST not like", value, "svrRequest");
            return (Criteria) this;
        }

        public Criteria andSvrRequestIn(List<String> values) {
            addCriterion("SVR_REQUEST in", values, "svrRequest");
            return (Criteria) this;
        }

        public Criteria andSvrRequestNotIn(List<String> values) {
            addCriterion("SVR_REQUEST not in", values, "svrRequest");
            return (Criteria) this;
        }

        public Criteria andSvrRequestBetween(String value1, String value2) {
            addCriterion("SVR_REQUEST between", value1, value2, "svrRequest");
            return (Criteria) this;
        }

        public Criteria andSvrRequestNotBetween(String value1, String value2) {
            addCriterion("SVR_REQUEST not between", value1, value2, "svrRequest");
            return (Criteria) this;
        }

        public Criteria andSvrCreateIdIsNull() {
            addCriterion("SVR_CREATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andSvrCreateIdIsNotNull() {
            addCriterion("SVR_CREATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSvrCreateIdEqualTo(BigDecimal value) {
            addCriterion("SVR_CREATE_ID =", value, "svrCreateId");
            return (Criteria) this;
        }

        public Criteria andSvrCreateIdNotEqualTo(BigDecimal value) {
            addCriterion("SVR_CREATE_ID <>", value, "svrCreateId");
            return (Criteria) this;
        }

        public Criteria andSvrCreateIdGreaterThan(BigDecimal value) {
            addCriterion("SVR_CREATE_ID >", value, "svrCreateId");
            return (Criteria) this;
        }

        public Criteria andSvrCreateIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SVR_CREATE_ID >=", value, "svrCreateId");
            return (Criteria) this;
        }

        public Criteria andSvrCreateIdLessThan(BigDecimal value) {
            addCriterion("SVR_CREATE_ID <", value, "svrCreateId");
            return (Criteria) this;
        }

        public Criteria andSvrCreateIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SVR_CREATE_ID <=", value, "svrCreateId");
            return (Criteria) this;
        }

        public Criteria andSvrCreateIdIn(List<BigDecimal> values) {
            addCriterion("SVR_CREATE_ID in", values, "svrCreateId");
            return (Criteria) this;
        }

        public Criteria andSvrCreateIdNotIn(List<BigDecimal> values) {
            addCriterion("SVR_CREATE_ID not in", values, "svrCreateId");
            return (Criteria) this;
        }

        public Criteria andSvrCreateIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SVR_CREATE_ID between", value1, value2, "svrCreateId");
            return (Criteria) this;
        }

        public Criteria andSvrCreateIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SVR_CREATE_ID not between", value1, value2, "svrCreateId");
            return (Criteria) this;
        }

        public Criteria andSvrCreateByIsNull() {
            addCriterion("SVR_CREATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andSvrCreateByIsNotNull() {
            addCriterion("SVR_CREATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andSvrCreateByEqualTo(String value) {
            addCriterion("SVR_CREATE_BY =", value, "svrCreateBy");
            return (Criteria) this;
        }

        public Criteria andSvrCreateByNotEqualTo(String value) {
            addCriterion("SVR_CREATE_BY <>", value, "svrCreateBy");
            return (Criteria) this;
        }

        public Criteria andSvrCreateByGreaterThan(String value) {
            addCriterion("SVR_CREATE_BY >", value, "svrCreateBy");
            return (Criteria) this;
        }

        public Criteria andSvrCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("SVR_CREATE_BY >=", value, "svrCreateBy");
            return (Criteria) this;
        }

        public Criteria andSvrCreateByLessThan(String value) {
            addCriterion("SVR_CREATE_BY <", value, "svrCreateBy");
            return (Criteria) this;
        }

        public Criteria andSvrCreateByLessThanOrEqualTo(String value) {
            addCriterion("SVR_CREATE_BY <=", value, "svrCreateBy");
            return (Criteria) this;
        }

        public Criteria andSvrCreateByLike(String value) {
            addCriterion("SVR_CREATE_BY like", value, "svrCreateBy");
            return (Criteria) this;
        }

        public Criteria andSvrCreateByNotLike(String value) {
            addCriterion("SVR_CREATE_BY not like", value, "svrCreateBy");
            return (Criteria) this;
        }

        public Criteria andSvrCreateByIn(List<String> values) {
            addCriterion("SVR_CREATE_BY in", values, "svrCreateBy");
            return (Criteria) this;
        }

        public Criteria andSvrCreateByNotIn(List<String> values) {
            addCriterion("SVR_CREATE_BY not in", values, "svrCreateBy");
            return (Criteria) this;
        }

        public Criteria andSvrCreateByBetween(String value1, String value2) {
            addCriterion("SVR_CREATE_BY between", value1, value2, "svrCreateBy");
            return (Criteria) this;
        }

        public Criteria andSvrCreateByNotBetween(String value1, String value2) {
            addCriterion("SVR_CREATE_BY not between", value1, value2, "svrCreateBy");
            return (Criteria) this;
        }

        public Criteria andSvrCreateDateIsNull() {
            addCriterion("SVR_CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSvrCreateDateIsNotNull() {
            addCriterion("SVR_CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSvrCreateDateEqualTo(Date value) {
            addCriterion("SVR_CREATE_DATE =", value, "svrCreateDate");
            return (Criteria) this;
        }

        public Criteria andSvrCreateDateNotEqualTo(Date value) {
            addCriterion("SVR_CREATE_DATE <>", value, "svrCreateDate");
            return (Criteria) this;
        }

        public Criteria andSvrCreateDateGreaterThan(Date value) {
            addCriterion("SVR_CREATE_DATE >", value, "svrCreateDate");
            return (Criteria) this;
        }

        public Criteria andSvrCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("SVR_CREATE_DATE >=", value, "svrCreateDate");
            return (Criteria) this;
        }

        public Criteria andSvrCreateDateLessThan(Date value) {
            addCriterion("SVR_CREATE_DATE <", value, "svrCreateDate");
            return (Criteria) this;
        }

        public Criteria andSvrCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("SVR_CREATE_DATE <=", value, "svrCreateDate");
            return (Criteria) this;
        }

        public Criteria andSvrCreateDateIn(List<Date> values) {
            addCriterion("SVR_CREATE_DATE in", values, "svrCreateDate");
            return (Criteria) this;
        }

        public Criteria andSvrCreateDateNotIn(List<Date> values) {
            addCriterion("SVR_CREATE_DATE not in", values, "svrCreateDate");
            return (Criteria) this;
        }

        public Criteria andSvrCreateDateBetween(Date value1, Date value2) {
            addCriterion("SVR_CREATE_DATE between", value1, value2, "svrCreateDate");
            return (Criteria) this;
        }

        public Criteria andSvrCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("SVR_CREATE_DATE not between", value1, value2, "svrCreateDate");
            return (Criteria) this;
        }

        public Criteria andSvrDueIdIsNull() {
            addCriterion("SVR_DUE_ID is null");
            return (Criteria) this;
        }

        public Criteria andSvrDueIdIsNotNull() {
            addCriterion("SVR_DUE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSvrDueIdEqualTo(BigDecimal value) {
            addCriterion("SVR_DUE_ID =", value, "svrDueId");
            return (Criteria) this;
        }

        public Criteria andSvrDueIdNotEqualTo(BigDecimal value) {
            addCriterion("SVR_DUE_ID <>", value, "svrDueId");
            return (Criteria) this;
        }

        public Criteria andSvrDueIdGreaterThan(BigDecimal value) {
            addCriterion("SVR_DUE_ID >", value, "svrDueId");
            return (Criteria) this;
        }

        public Criteria andSvrDueIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SVR_DUE_ID >=", value, "svrDueId");
            return (Criteria) this;
        }

        public Criteria andSvrDueIdLessThan(BigDecimal value) {
            addCriterion("SVR_DUE_ID <", value, "svrDueId");
            return (Criteria) this;
        }

        public Criteria andSvrDueIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SVR_DUE_ID <=", value, "svrDueId");
            return (Criteria) this;
        }

        public Criteria andSvrDueIdIn(List<BigDecimal> values) {
            addCriterion("SVR_DUE_ID in", values, "svrDueId");
            return (Criteria) this;
        }

        public Criteria andSvrDueIdNotIn(List<BigDecimal> values) {
            addCriterion("SVR_DUE_ID not in", values, "svrDueId");
            return (Criteria) this;
        }

        public Criteria andSvrDueIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SVR_DUE_ID between", value1, value2, "svrDueId");
            return (Criteria) this;
        }

        public Criteria andSvrDueIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SVR_DUE_ID not between", value1, value2, "svrDueId");
            return (Criteria) this;
        }

        public Criteria andSvrDueToIsNull() {
            addCriterion("SVR_DUE_TO is null");
            return (Criteria) this;
        }

        public Criteria andSvrDueToIsNotNull() {
            addCriterion("SVR_DUE_TO is not null");
            return (Criteria) this;
        }

        public Criteria andSvrDueToEqualTo(String value) {
            addCriterion("SVR_DUE_TO =", value, "svrDueTo");
            return (Criteria) this;
        }

        public Criteria andSvrDueToNotEqualTo(String value) {
            addCriterion("SVR_DUE_TO <>", value, "svrDueTo");
            return (Criteria) this;
        }

        public Criteria andSvrDueToGreaterThan(String value) {
            addCriterion("SVR_DUE_TO >", value, "svrDueTo");
            return (Criteria) this;
        }

        public Criteria andSvrDueToGreaterThanOrEqualTo(String value) {
            addCriterion("SVR_DUE_TO >=", value, "svrDueTo");
            return (Criteria) this;
        }

        public Criteria andSvrDueToLessThan(String value) {
            addCriterion("SVR_DUE_TO <", value, "svrDueTo");
            return (Criteria) this;
        }

        public Criteria andSvrDueToLessThanOrEqualTo(String value) {
            addCriterion("SVR_DUE_TO <=", value, "svrDueTo");
            return (Criteria) this;
        }

        public Criteria andSvrDueToLike(String value) {
            addCriterion("SVR_DUE_TO like", value, "svrDueTo");
            return (Criteria) this;
        }

        public Criteria andSvrDueToNotLike(String value) {
            addCriterion("SVR_DUE_TO not like", value, "svrDueTo");
            return (Criteria) this;
        }

        public Criteria andSvrDueToIn(List<String> values) {
            addCriterion("SVR_DUE_TO in", values, "svrDueTo");
            return (Criteria) this;
        }

        public Criteria andSvrDueToNotIn(List<String> values) {
            addCriterion("SVR_DUE_TO not in", values, "svrDueTo");
            return (Criteria) this;
        }

        public Criteria andSvrDueToBetween(String value1, String value2) {
            addCriterion("SVR_DUE_TO between", value1, value2, "svrDueTo");
            return (Criteria) this;
        }

        public Criteria andSvrDueToNotBetween(String value1, String value2) {
            addCriterion("SVR_DUE_TO not between", value1, value2, "svrDueTo");
            return (Criteria) this;
        }

        public Criteria andSvrDueDateIsNull() {
            addCriterion("SVR_DUE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSvrDueDateIsNotNull() {
            addCriterion("SVR_DUE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSvrDueDateEqualTo(Date value) {
            addCriterion("SVR_DUE_DATE =", value, "svrDueDate");
            return (Criteria) this;
        }

        public Criteria andSvrDueDateNotEqualTo(Date value) {
            addCriterion("SVR_DUE_DATE <>", value, "svrDueDate");
            return (Criteria) this;
        }

        public Criteria andSvrDueDateGreaterThan(Date value) {
            addCriterion("SVR_DUE_DATE >", value, "svrDueDate");
            return (Criteria) this;
        }

        public Criteria andSvrDueDateGreaterThanOrEqualTo(Date value) {
            addCriterion("SVR_DUE_DATE >=", value, "svrDueDate");
            return (Criteria) this;
        }

        public Criteria andSvrDueDateLessThan(Date value) {
            addCriterion("SVR_DUE_DATE <", value, "svrDueDate");
            return (Criteria) this;
        }

        public Criteria andSvrDueDateLessThanOrEqualTo(Date value) {
            addCriterion("SVR_DUE_DATE <=", value, "svrDueDate");
            return (Criteria) this;
        }

        public Criteria andSvrDueDateIn(List<Date> values) {
            addCriterion("SVR_DUE_DATE in", values, "svrDueDate");
            return (Criteria) this;
        }

        public Criteria andSvrDueDateNotIn(List<Date> values) {
            addCriterion("SVR_DUE_DATE not in", values, "svrDueDate");
            return (Criteria) this;
        }

        public Criteria andSvrDueDateBetween(Date value1, Date value2) {
            addCriterion("SVR_DUE_DATE between", value1, value2, "svrDueDate");
            return (Criteria) this;
        }

        public Criteria andSvrDueDateNotBetween(Date value1, Date value2) {
            addCriterion("SVR_DUE_DATE not between", value1, value2, "svrDueDate");
            return (Criteria) this;
        }

        public Criteria andSvrDealIsNull() {
            addCriterion("SVR_DEAL is null");
            return (Criteria) this;
        }

        public Criteria andSvrDealIsNotNull() {
            addCriterion("SVR_DEAL is not null");
            return (Criteria) this;
        }

        public Criteria andSvrDealEqualTo(String value) {
            addCriterion("SVR_DEAL =", value, "svrDeal");
            return (Criteria) this;
        }

        public Criteria andSvrDealNotEqualTo(String value) {
            addCriterion("SVR_DEAL <>", value, "svrDeal");
            return (Criteria) this;
        }

        public Criteria andSvrDealGreaterThan(String value) {
            addCriterion("SVR_DEAL >", value, "svrDeal");
            return (Criteria) this;
        }

        public Criteria andSvrDealGreaterThanOrEqualTo(String value) {
            addCriterion("SVR_DEAL >=", value, "svrDeal");
            return (Criteria) this;
        }

        public Criteria andSvrDealLessThan(String value) {
            addCriterion("SVR_DEAL <", value, "svrDeal");
            return (Criteria) this;
        }

        public Criteria andSvrDealLessThanOrEqualTo(String value) {
            addCriterion("SVR_DEAL <=", value, "svrDeal");
            return (Criteria) this;
        }

        public Criteria andSvrDealLike(String value) {
            addCriterion("SVR_DEAL like", value, "svrDeal");
            return (Criteria) this;
        }

        public Criteria andSvrDealNotLike(String value) {
            addCriterion("SVR_DEAL not like", value, "svrDeal");
            return (Criteria) this;
        }

        public Criteria andSvrDealIn(List<String> values) {
            addCriterion("SVR_DEAL in", values, "svrDeal");
            return (Criteria) this;
        }

        public Criteria andSvrDealNotIn(List<String> values) {
            addCriterion("SVR_DEAL not in", values, "svrDeal");
            return (Criteria) this;
        }

        public Criteria andSvrDealBetween(String value1, String value2) {
            addCriterion("SVR_DEAL between", value1, value2, "svrDeal");
            return (Criteria) this;
        }

        public Criteria andSvrDealNotBetween(String value1, String value2) {
            addCriterion("SVR_DEAL not between", value1, value2, "svrDeal");
            return (Criteria) this;
        }

        public Criteria andSvrDealIdIsNull() {
            addCriterion("SVR_DEAL_ID is null");
            return (Criteria) this;
        }

        public Criteria andSvrDealIdIsNotNull() {
            addCriterion("SVR_DEAL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSvrDealIdEqualTo(BigDecimal value) {
            addCriterion("SVR_DEAL_ID =", value, "svrDealId");
            return (Criteria) this;
        }

        public Criteria andSvrDealIdNotEqualTo(BigDecimal value) {
            addCriterion("SVR_DEAL_ID <>", value, "svrDealId");
            return (Criteria) this;
        }

        public Criteria andSvrDealIdGreaterThan(BigDecimal value) {
            addCriterion("SVR_DEAL_ID >", value, "svrDealId");
            return (Criteria) this;
        }

        public Criteria andSvrDealIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SVR_DEAL_ID >=", value, "svrDealId");
            return (Criteria) this;
        }

        public Criteria andSvrDealIdLessThan(BigDecimal value) {
            addCriterion("SVR_DEAL_ID <", value, "svrDealId");
            return (Criteria) this;
        }

        public Criteria andSvrDealIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SVR_DEAL_ID <=", value, "svrDealId");
            return (Criteria) this;
        }

        public Criteria andSvrDealIdIn(List<BigDecimal> values) {
            addCriterion("SVR_DEAL_ID in", values, "svrDealId");
            return (Criteria) this;
        }

        public Criteria andSvrDealIdNotIn(List<BigDecimal> values) {
            addCriterion("SVR_DEAL_ID not in", values, "svrDealId");
            return (Criteria) this;
        }

        public Criteria andSvrDealIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SVR_DEAL_ID between", value1, value2, "svrDealId");
            return (Criteria) this;
        }

        public Criteria andSvrDealIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SVR_DEAL_ID not between", value1, value2, "svrDealId");
            return (Criteria) this;
        }

        public Criteria andSvrDealByIsNull() {
            addCriterion("SVR_DEAL_BY is null");
            return (Criteria) this;
        }

        public Criteria andSvrDealByIsNotNull() {
            addCriterion("SVR_DEAL_BY is not null");
            return (Criteria) this;
        }

        public Criteria andSvrDealByEqualTo(String value) {
            addCriterion("SVR_DEAL_BY =", value, "svrDealBy");
            return (Criteria) this;
        }

        public Criteria andSvrDealByNotEqualTo(String value) {
            addCriterion("SVR_DEAL_BY <>", value, "svrDealBy");
            return (Criteria) this;
        }

        public Criteria andSvrDealByGreaterThan(String value) {
            addCriterion("SVR_DEAL_BY >", value, "svrDealBy");
            return (Criteria) this;
        }

        public Criteria andSvrDealByGreaterThanOrEqualTo(String value) {
            addCriterion("SVR_DEAL_BY >=", value, "svrDealBy");
            return (Criteria) this;
        }

        public Criteria andSvrDealByLessThan(String value) {
            addCriterion("SVR_DEAL_BY <", value, "svrDealBy");
            return (Criteria) this;
        }

        public Criteria andSvrDealByLessThanOrEqualTo(String value) {
            addCriterion("SVR_DEAL_BY <=", value, "svrDealBy");
            return (Criteria) this;
        }

        public Criteria andSvrDealByLike(String value) {
            addCriterion("SVR_DEAL_BY like", value, "svrDealBy");
            return (Criteria) this;
        }

        public Criteria andSvrDealByNotLike(String value) {
            addCriterion("SVR_DEAL_BY not like", value, "svrDealBy");
            return (Criteria) this;
        }

        public Criteria andSvrDealByIn(List<String> values) {
            addCriterion("SVR_DEAL_BY in", values, "svrDealBy");
            return (Criteria) this;
        }

        public Criteria andSvrDealByNotIn(List<String> values) {
            addCriterion("SVR_DEAL_BY not in", values, "svrDealBy");
            return (Criteria) this;
        }

        public Criteria andSvrDealByBetween(String value1, String value2) {
            addCriterion("SVR_DEAL_BY between", value1, value2, "svrDealBy");
            return (Criteria) this;
        }

        public Criteria andSvrDealByNotBetween(String value1, String value2) {
            addCriterion("SVR_DEAL_BY not between", value1, value2, "svrDealBy");
            return (Criteria) this;
        }

        public Criteria andSvrDealDateIsNull() {
            addCriterion("SVR_DEAL_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSvrDealDateIsNotNull() {
            addCriterion("SVR_DEAL_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSvrDealDateEqualTo(Date value) {
            addCriterion("SVR_DEAL_DATE =", value, "svrDealDate");
            return (Criteria) this;
        }

        public Criteria andSvrDealDateNotEqualTo(Date value) {
            addCriterion("SVR_DEAL_DATE <>", value, "svrDealDate");
            return (Criteria) this;
        }

        public Criteria andSvrDealDateGreaterThan(Date value) {
            addCriterion("SVR_DEAL_DATE >", value, "svrDealDate");
            return (Criteria) this;
        }

        public Criteria andSvrDealDateGreaterThanOrEqualTo(Date value) {
            addCriterion("SVR_DEAL_DATE >=", value, "svrDealDate");
            return (Criteria) this;
        }

        public Criteria andSvrDealDateLessThan(Date value) {
            addCriterion("SVR_DEAL_DATE <", value, "svrDealDate");
            return (Criteria) this;
        }

        public Criteria andSvrDealDateLessThanOrEqualTo(Date value) {
            addCriterion("SVR_DEAL_DATE <=", value, "svrDealDate");
            return (Criteria) this;
        }

        public Criteria andSvrDealDateIn(List<Date> values) {
            addCriterion("SVR_DEAL_DATE in", values, "svrDealDate");
            return (Criteria) this;
        }

        public Criteria andSvrDealDateNotIn(List<Date> values) {
            addCriterion("SVR_DEAL_DATE not in", values, "svrDealDate");
            return (Criteria) this;
        }

        public Criteria andSvrDealDateBetween(Date value1, Date value2) {
            addCriterion("SVR_DEAL_DATE between", value1, value2, "svrDealDate");
            return (Criteria) this;
        }

        public Criteria andSvrDealDateNotBetween(Date value1, Date value2) {
            addCriterion("SVR_DEAL_DATE not between", value1, value2, "svrDealDate");
            return (Criteria) this;
        }

        public Criteria andSvrResultIsNull() {
            addCriterion("SVR_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andSvrResultIsNotNull() {
            addCriterion("SVR_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andSvrResultEqualTo(String value) {
            addCriterion("SVR_RESULT =", value, "svrResult");
            return (Criteria) this;
        }

        public Criteria andSvrResultNotEqualTo(String value) {
            addCriterion("SVR_RESULT <>", value, "svrResult");
            return (Criteria) this;
        }

        public Criteria andSvrResultGreaterThan(String value) {
            addCriterion("SVR_RESULT >", value, "svrResult");
            return (Criteria) this;
        }

        public Criteria andSvrResultGreaterThanOrEqualTo(String value) {
            addCriterion("SVR_RESULT >=", value, "svrResult");
            return (Criteria) this;
        }

        public Criteria andSvrResultLessThan(String value) {
            addCriterion("SVR_RESULT <", value, "svrResult");
            return (Criteria) this;
        }

        public Criteria andSvrResultLessThanOrEqualTo(String value) {
            addCriterion("SVR_RESULT <=", value, "svrResult");
            return (Criteria) this;
        }

        public Criteria andSvrResultLike(String value) {
            addCriterion("SVR_RESULT like", value, "svrResult");
            return (Criteria) this;
        }

        public Criteria andSvrResultNotLike(String value) {
            addCriterion("SVR_RESULT not like", value, "svrResult");
            return (Criteria) this;
        }

        public Criteria andSvrResultIn(List<String> values) {
            addCriterion("SVR_RESULT in", values, "svrResult");
            return (Criteria) this;
        }

        public Criteria andSvrResultNotIn(List<String> values) {
            addCriterion("SVR_RESULT not in", values, "svrResult");
            return (Criteria) this;
        }

        public Criteria andSvrResultBetween(String value1, String value2) {
            addCriterion("SVR_RESULT between", value1, value2, "svrResult");
            return (Criteria) this;
        }

        public Criteria andSvrResultNotBetween(String value1, String value2) {
            addCriterion("SVR_RESULT not between", value1, value2, "svrResult");
            return (Criteria) this;
        }

        public Criteria andSvrSatisfyIsNull() {
            addCriterion("SVR_SATISFY is null");
            return (Criteria) this;
        }

        public Criteria andSvrSatisfyIsNotNull() {
            addCriterion("SVR_SATISFY is not null");
            return (Criteria) this;
        }

        public Criteria andSvrSatisfyEqualTo(Long value) {
            addCriterion("SVR_SATISFY =", value, "svrSatisfy");
            return (Criteria) this;
        }

        public Criteria andSvrSatisfyNotEqualTo(Long value) {
            addCriterion("SVR_SATISFY <>", value, "svrSatisfy");
            return (Criteria) this;
        }

        public Criteria andSvrSatisfyGreaterThan(Long value) {
            addCriterion("SVR_SATISFY >", value, "svrSatisfy");
            return (Criteria) this;
        }

        public Criteria andSvrSatisfyGreaterThanOrEqualTo(Long value) {
            addCriterion("SVR_SATISFY >=", value, "svrSatisfy");
            return (Criteria) this;
        }

        public Criteria andSvrSatisfyLessThan(Long value) {
            addCriterion("SVR_SATISFY <", value, "svrSatisfy");
            return (Criteria) this;
        }

        public Criteria andSvrSatisfyLessThanOrEqualTo(Long value) {
            addCriterion("SVR_SATISFY <=", value, "svrSatisfy");
            return (Criteria) this;
        }

        public Criteria andSvrSatisfyIn(List<Long> values) {
            addCriterion("SVR_SATISFY in", values, "svrSatisfy");
            return (Criteria) this;
        }

        public Criteria andSvrSatisfyNotIn(List<Long> values) {
            addCriterion("SVR_SATISFY not in", values, "svrSatisfy");
            return (Criteria) this;
        }

        public Criteria andSvrSatisfyBetween(Long value1, Long value2) {
            addCriterion("SVR_SATISFY between", value1, value2, "svrSatisfy");
            return (Criteria) this;
        }

        public Criteria andSvrSatisfyNotBetween(Long value1, Long value2) {
            addCriterion("SVR_SATISFY not between", value1, value2, "svrSatisfy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CST_SERVICE
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 29 10:30:00 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CST_SERVICE
     *
     * @mbg.generated Tue Aug 29 10:30:00 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}